name: "Waveshare PoE Hat"
description: "Waveshare PoE Hat add-on for screen and fan support!"
version: "1.0.0"
full_access: true
slug: "waveshare_poe"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386